create table if not exists staging_pathway_learning_progress(
    dw_id                 bigint,
    _trace_id             varchar(36),
    event_type            varchar(100),
    created_time          timestamp encode az64,
    dw_created_time       timestamp encode az64,
    date_dw_id            bigint encode az64,
    experience_id         varchar(36),
    learning_session_id   varchar(36),
    content_id            varchar(36),
    learning_objective_id varchar(36),
    student_id            varchar(36) distkey,
    subject_id            varchar(36),
    student_grade_id      varchar(36),
    curriculum_subject_id varchar(36),
    curriculum_grade_id   varchar(36),
    curriculum_id         varchar(36),
    tenant_id             varchar(36),
    school_id             varchar(36),
    student_section_id    varchar(36),
    learning_path_id      varchar(36),
    start_time            timestamp encode az64,
    end_time              timestamp encode az64,
    total_time            double precision,
    score                 integer encode az64,
    stars                 integer encode az64,
    lesson_type           varchar(50),
    retry                 boolean,
    outside_of_school     boolean,
    attempt               integer encode az64,
    learning_experience_flag             boolean,
    trimester_order       varchar(20),
    academic_year_id      varchar(256),
    content_academic_year varchar(20),
    time_spent            integer encode az64,
    instructional_plan_id varchar(36),
    class_id              varchar(36),
    lesson_category       varchar(40),
    level               varchar(20),
    abbreviation          varchar(100),
    activity_template_id  varchar(100),
    activity_type         varchar(100),
    activity_component_type varchar(100),
    exit_ticket           boolean,
    main_component        boolean,
    completion_node       boolean,
    total_score           numeric(10, 4) encode az64,
    activity_completed   boolean,
    material_id           varchar(36),
    material_type         varchar(20),
    state                 smallint encode az64,
    total_stars           smallint encode az64,
    open_path_enabled     boolean     default false,
    source                varchar(10),
    teaching_period_id    varchar(36),
    academic_year         varchar(10),
    assessment_id         varchar(36),
    is_in_class_game_experience             boolean     default false,
    is_additional_resource  boolean     default false,
    bonus_stars           integer     default -1 encode az64,
    bonus_stars_scheme    varchar(40) default 'NA'::character varying
)
    sortkey (school_id, student_grade_id, student_section_id);
