create table if not exists staging_adaptive_practice_progress(
    dw_id                   bigint,
    event_type              Varchar(100),
    _trace_id               varchar(36),
    tenant_id               varchar(36),
    date_dw_id              bigint,
    uuid                    Varchar(36),
    created_time            timestamp,
    dw_created_time         timestamp,
    student_id              Varchar(36),
    class_id                Varchar(36),
    school_id               Varchar(36),
    pathway_id              Varchar(36),
    level_id                Varchar(36),
    academic_year_tag       Varchar(40),
    session_id              Varchar(36),
    ml_session_id           Varchar(36),
    level_proficiency_score double precision,
    level_proficiency_tier  Varchar(50),
    assessment_id           Varchar(36),
    session_attempt         int,
    stars                   int,
    time_spent              int,
    question_id             Varchar(36),
    question_skill_id       Varchar(36),
    question_difficulty_label   varchar(30),
    skill_proficiency_tier  Varchar(40),
    skill_proficiency_score double precision,
    answer_score            double precision,
    time_spent_on_question  int,
    hint_used               boolean,
    is_answer_correct       boolean,
    next_question_id        Varchar(36),
    attempt_number          int,
    next_question_skill_id  Varchar(36),
    next_question_difficulty_label Varchar(30)
    );
