create table if not exists staging_student_proficiency_tracker(
    dw_id                   bigint,
    event_type              Varchar(100),
    _trace_id               varchar(36),
    tenant_id               varchar(36),
    date_dw_id              bigint,
    uuid                    Varchar(36),
    created_time            timestamp,
    dw_created_time         timestamp,
    student_id              Varchar(36),
    class_id                Varchar(36),
    school_id               Varchar(36),
    pathway_id              Varchar(36),
    level_id                Varchar(36),
    academic_year_tag       Varchar(40),
    session_id              Varchar(36),
    ml_session_id           Varchar(36),
    level_proficiency_score double precision,
    level_proficiency_tier  Varchar(50),
    assessment_id           Varchar(36),
    session_attempt         int,
    stars                   int,
    time_spent              int,
    skill_proficiency_tier  Varchar(40),
    skill_proficiency_score double precision,
    skill_id                Varchar(36),
    status                  varchar(50),
    previous_proficiency_tier Varchar(50)
);