package com.alefeducation.schema.adt

case class NextQuestion(id: String,
                        occurredOn: Long,
                        learningSessionId: String,
                        studentId: String,
                        questionPoolId: String,
                        response: String,
                        proficiency: Double,
                        standardError: Float,
                        nextQuestion: String,
                        timeSpent: Double,
                        intestProgress: Double,
                        currentQuestion: String,
                        curriculumSubjectId: Long,
                        curriculumSubjectName: String,
                        breakdown: String,
                        language: String,
                        grade: Int,
                        gradeId: String,
                        academicYear: Int,
                        academicYearId: String,
                        academicTerm: Int,
                        attempt: Int,
                        classSubjectName: String,
                        skill: String
)

case class StudentReport(id: String,
                        occurredOn: Long,
                        learningSessionId: String,
                        studentId: String,
                        questionPoolId: String,
                        finalProficiency: Float,
                        finalUncertainty: Float,
                        finalCategory: String,
                        finalGrade: Int,
                        finalStandardError: Float,
                        finalScore: Float,
                        forecastScore: Float,
                        finalResult: String,      
                        totalTimespent: Float, 
                        academicYear: Int,
                        academicTerm: Int,
                        testId: String,
                        curriculumSubjectId: Long,
                        curriculumSubjectName: String,
                        language: String,
                        framework: String,
                        breakdown: String,
                        schoolId: String,
                        attempt: Int,
                        grade: Int,
                        gradeId: String,
                        academicYearId: String,
                        secondaryResult: String,
                        classSubjectName: String,
                        skill: String
)

case class AttemptThresholdCreated(id: String,
                                   occurredOn: Long,
                                   academicYearId: String,
                                   schoolId: String,
                                   schoolName: String,
                                   status: String,
                                   numberOfAttempts: Int,
                                   attempts: List[Attempt]
)

case class Attempt(attemptNumber: Int,
                   attemptTitle: String,
                   startTime: Long,
                   endTime: Long
)
