CREATE GROUP alefdw_admins;

GRANT USAGE ON SCHEMA alefdw_stage TO GROUP alefdw_admins;
GRANT USAGE ON SCHEMA alefdw TO GROUP alefdw_admins;
GRANT USAGE ON SCHEMA backups TO GROUP alefdw_admins;
GRANT CREATE ON SCHEMA backups TO GROUP alefdw_admins;
GRANT DELETE ON ALL TABLES IN SCHEMA alefdw_stage TO GROUP alefdw_admins;
GRANT UPDATE ON ALL TABLES IN SCHEMA alefdw_stage TO GROUP alefdw_admins;
GRANT SELECT ON ALL TABLES IN SCHEMA alefdw_stage TO GROUP alefdw_admins;
GRANT INSERT ON ALL TABLES IN SCHEMA alefdw_stage TO GROUP alefdw_admins;

ALTER DEFAULT PRIVILEGES IN SCHEMA alefdw_stage GRANT DELETE ON TABLES TO GROUP alefdw_admins;
ALTER DEFAULT PRIVILEGES IN SCHEMA alefdw_stage GRANT UPDATE ON TABLES TO GROUP alefdw_admins;
ALTER DEFAULT PRIVILEGES IN SCHEMA alefdw_stage GRANT SELECT ON TABLES TO GROUP alefdw_admins;
ALTER DEFAULT PRIVILEGES IN SCHEMA alefdw_stage GRANT INSERT ON TABLES TO GROUP alefdw_admins;

ALTER DEFAULT PRIVILEGES IN SCHEMA alefdw_stage FOR USER flyway_migration_prd GRANT DELETE ON TABLES TO GROUP alefdw_admins;
ALTER DEFAULT PRIVILEGES IN SCHEMA alefdw_stage FOR USER flyway_migration_prd GRANT UPDATE ON TABLES TO GROUP alefdw_admins;
ALTER DEFAULT PRIVILEGES IN SCHEMA alefdw_stage FOR USER flyway_migration_prd GRANT SELECT ON TABLES TO GROUP alefdw_admins;
ALTER DEFAULT PRIVILEGES IN SCHEMA alefdw_stage FOR USER flyway_migration_prd GRANT INSERT ON TABLES TO GROUP alefdw_admins;


GRANT DELETE ON ALL TABLES IN SCHEMA alefdw TO GROUP alefdw_admins;
GRANT UPDATE ON ALL TABLES IN SCHEMA alefdw TO GROUP alefdw_admins;
GRANT SELECT ON ALL TABLES IN SCHEMA alefdw TO GROUP alefdw_admins;
GRANT INSERT ON ALL TABLES IN SCHEMA alefdw TO GROUP alefdw_admins;

ALTER DEFAULT PRIVILEGES IN SCHEMA alefdw GRANT DELETE ON TABLES TO GROUP alefdw_admins;
ALTER DEFAULT PRIVILEGES IN SCHEMA alefdw GRANT UPDATE ON TABLES TO GROUP alefdw_admins;
ALTER DEFAULT PRIVILEGES IN SCHEMA alefdw GRANT SELECT ON TABLES TO GROUP alefdw_admins;
ALTER DEFAULT PRIVILEGES IN SCHEMA alefdw GRANT INSERT ON TABLES TO GROUP alefdw_admins;

ALTER DEFAULT PRIVILEGES IN SCHEMA alefdw FOR USER flyway_migration_prd GRANT DELETE ON TABLES TO GROUP alefdw_admins;
ALTER DEFAULT PRIVILEGES IN SCHEMA alefdw FOR USER flyway_migration_prd GRANT UPDATE ON TABLES TO GROUP alefdw_admins;
ALTER DEFAULT PRIVILEGES IN SCHEMA alefdw FOR USER flyway_migration_prd GRANT SELECT ON TABLES TO GROUP alefdw_admins;
ALTER DEFAULT PRIVILEGES IN SCHEMA alefdw FOR USER flyway_migration_prd GRANT INSERT ON TABLES TO GROUP alefdw_admins;