package com.alefeducation.schema.tutor

case class TutorContextCreated(userId: String,
                               `role`: String,
                               contextId: String,
                               schoolId: String,
                               gradeId: String,
                               grade: Int,
                               subjectId: String,
                               subject: String,
                               language: String,
                               tutorLocked: Boolean,
                               occurredOn: String)

case class TutorSession(userId: String,
                        role: String,
                        contextId: String,
                        schoolId: String,
                        gradeId: String,
                        grade: Int,
                        subjectId: String,
                        subject: String,
                        language: String,
                        sessionId: String,
                        sessionStatus: String,
                        materialId: String,
                        materialType: String,
                        activityId: String,
                        activityStatus: String,
                        levelId: String,
                        outcomeId: String,
                        learningSessionId: String,
                        sessionMessageLimitReached: Boolean,
                        occurredOn: String)

case class TutorConversation(userId: String,
                             role: String,
                             contextId: String,
                             schoolId: String,
                             gradeId: String,
                             grade: Int,
                             subjectId: String,
                             subject: String,
                             language: String,
                             sessionId: String,
                             sessionStatus: String,
                             materialId: String,
                             materialType: String,
                             activityId: String,
                             activityStatus: String,
                             levelId: String,
                             outcomeId: String,
                             messageId: String,
                             conversationId: String,
                             conversationMaxTokens: Int,
                             conversationTokenCount: Int,
                             systemPrompt: String,
                             systemPromptTokens: Int,
                             suggestionsPrompt: String,
                             suggestionsPromptTokens: Int,
                             messageLanguage: String,
                             messageTokens: Int,
                             messageFeedback: String,
                             userMessage: String,
                             userMessageSource: String,
                             userMessageTokens: Int,
                             userMessageTimestamp: String,
                             userMessageClassification: String,
                             botMessage: String,
                             botMessageSource: String,
                             botMessageTokens: Int,
                             botMessageTimestamp: String,
                             botMessageResponseTime: Double,
                             botMessageConfidence: Double,
                             activityPageContextId: String,
                             studentLocation: String,
                             suggestionClicked: Boolean,
                             clickedSuggestionId: String,
                             occurredOn: String)

case class Suggestion(suggestionId: String, suggestionQuestion: String, suggestionClicked: Boolean)

case class TutorSuggestions(userId: String,
                            sessionId: String,
                            conversationId: String,
                            messageId: String,
                            responseTime: Double,
                            successParserTokens: Int,
                            failureParserTokens: Int,
                            suggestions: List[Suggestion],
                            occurredOn: String)

case class TutorOnboarding(userId: String,
                           questionId: String,
                           questionCategory: String,
                           userResponse: String,
                           userFreeTextResponse: Boolean,
                           onboardingSkipped: Boolean,
                           onboardingComplete: Boolean,
                           occurredOn: String)

case class TutorCallToAction(userId: String,
                            message: String,
                            actionType: String,
                            actionMetadata: String,
                            accepted: Boolean,
                            occurredOn: String)

case class TutorAnalogous(userId: String,
                    sessionId: String,
                    conversationId: String,
                    messageId: String,
                    analogous: String,
                    userInterest: String,
                    occurredOn: String)

  case class TutorTranslation(userId: String,
                            sessionId: String,
                            conversationId: String,
                            messageId: String,
                            translation: String,
                            translationLanguage: String,
                            occurredOn: String)

  case class TutorSimplification(userId: String,
                              sessionId: String,
                              conversationId: String,
                              messageId: String,
                              simplification: String,
                              occurredOn: String)

  case class TutorChallengeQuestions(userId: String,
                                sessionId: String,
                                conversationId: String,
                                messageId: String,
                                botQuestionMessage: String,
                                botQuestionTokens: Int,
                                botQuestionId: String,
                                botQuestionTimestamp: String,
                                botQuestionSource: String,
                                occurredOn: String)


  case class TutorChallengeQuestionEvaluation(userId: String,
                                       sessionId: String,
                                       conversationId: String,
                                       messageId: String,
                                       botQuestionId: String,
                                       userAttemptMessage: String,
                                       userAttemptTokens: Int,
                                       userAttemptId: String,
                                       userAttemptTimestamp: String,
                                       userAttemptSource: String,
                                       userAttemptNumber: Int,
                                       userRemainingAttempts: Int,
                                       userAttemptIsCorrect: Boolean,
                                       occurredOn: String)

case class TutorSkipOnboarding(userId: String,
                     questionId: String,
                     occurredOn: String)
