CREATE TABLE IF NOT EXISTS fact_item_transaction (
    fit_dw_id BIGINT,
    fit_created_time TIMESTAMP,
    fit_dw_created_time TIMESTAMP,
    fit_date_dw_id BIGINT,
    fit_id VARCHAR(36),
    fit_available_stars INT,
    fit_item_cost INT,
    fit_star_balance INT,
    fit_item_id VARCHAR(36),
    fit_item_dw_id BIGINT,
    fit_item_type VARCHAR(50),
    fit_student_id VARCHAR(36),
    fit_student_dw_id BIGINT,
    fit_tenant_id VARCHAR(36),
    fit_tenant_dw_id BIGINT,
    fit_school_id VARCHAR(36),
    fit_school_dw_id BIGINT,
    fit_grade_id VARCHAR(36),
    fit_grade_dw_id BIGINT,
    fit_section_id VARCHAR(36),
    fit_section_dw_id BIGINT,
    fit_academic_year_id VARCHAR(36),
    fit_academic_year_dw_id BIGINT,
    fit_academic_year INTEGER
);
