CREATE TABLE dim_avatar_v2 (
  avatar_dw_id BIGINT NOT NULL,
  avatar_id VARCHAR(36) NOT NULL,
  avatar_file_id VARCHAR(36) NOT NULL,
  avatar_created_time TIMESTAMP,
  avatar_deleted_time TIMESTAMP,
  avatar_dw_created_time TIMESTAMP,
  avatar_updated_time TIMESTAMP,
  avatar_dw_updated_time TIMESTAMP,
  avatar_app_status VARCHAR(20),
  avatar_status INT,
  avatar_type VARCHAR(36),
  avatar_name VARCHAR(256),
  avatar_description VARCHAR(36),
  avatar_valid_from TIMESTAMP,
  avatar_valid_till TIMESTAMP,
  avatar_category VARCHAR(20),
  avatar_star_cost INT,
  avatar_is_enabled_for_all_orgs BOOLEAN
);

CREATE TABLE IF NOT EXISTS dim_avatar_layer_customization_v2 (
ala_dw_id BIGINT NOT NULL,
ala_created_time TIMESTAMP NOT NULL,
ala_dw_created_time TIMESTAMP NOT NULL,
ala_deleted_time TIMESTAMP,
ala_updated_time TIMESTAMP,
ala_dw_updated_time TIMESTAMP,
ala_status INT NOT NULL,
ala_avatar_id VARCHAR(36) NOT NULL,
ala_layer_id VARCHAR(36) NOT NULL
);

CREATE TABLE IF NOT EXISTS fact_item_purchase_v2 (
  fip_dw_id BIGINT,
  fip_created_time TIMESTAMP,
  fip_dw_created_time TIMESTAMP,
  fip_date_dw_id BIGINT,
  fip_id VARCHAR(36),
  fip_item_id VARCHAR(36),
  fip_item_dw_id BIGINT,
  fip_item_type VARCHAR(50),
  fip_item_title VARCHAR(50),
  fip_item_description VARCHAR(50),
  fip_transaction_id VARCHAR(36),
  fip_school_id VARCHAR(36),
  fip_school_dw_id BIGINT,
  fip_grade_id VARCHAR(36),
  fip_grade_dw_id BIGINT,
  fip_section_id VARCHAR(36),
  fip_section_dw_id BIGINT,
  fip_academic_year_id VARCHAR(36),
  fip_academic_year_dw_id BIGINT,
  fip_academic_year INTEGER,
  fip_student_id VARCHAR(36),
  fip_student_dw_id BIGINT,
  fip_tenant_id VARCHAR(36),
  fip_tenant_dw_id BIGINT,
  fip_redeemed_stars INTEGER
);

CREATE TABLE dim_pathway_target_v2
(
  pt_dw_id  bigint,
  pt_id VARCHAR(36),
  pt_created_time Timestamp,
  pt_dw_created_time  Timestamp,
  pt_status  Int,
  pt_active_until  Timestamp,
  pt_target_id  VARCHAR(36),
  pt_target_dw_id  bigint,
  pt_target_state VARCHAR(20),
  pt_start_date VARCHAR(10),
  pt_end_date VARCHAR(10),
  pt_tenant_id  VARCHAR(36),
  pt_tenant_dw_id bigint,
  pt_school_id  VARCHAR(36),
  pt_school_dw_id bigint,
  pt_grade_id VARCHAR(36),
  pt_grade_dw_id  bigint,
  pt_class_id VARCHAR(36),
  pt_class_dw_id  bigint,
  pt_teacher_id VARCHAR(36),
  pt_teacher_dw_id  bigint,
  pt_pathway_id VARCHAR(36),
  pt_pathway_dw_id  bigint
);
