CREATE TABLE IF NOT EXISTS dim_testpart (
  dw_id BIGINT,
  _trace_id VARCHAR(36),
  tenant_id VARCHAR(36),
  event_type VARCHAR(50),
  created_time TIMESTAMP,
  dw_created_time TIMESTAMP,
  active_until TIMESTAMP,
  status INT,
  published_on TIMESTAMP,
  id VARCHAR(36),
  version_id VARCHAR(36),
  version BIGINT,
  title VARCHAR(768),
  reference_code VARCHAR(50),
  app_status VARCHAR(36),
  user_id VARCHAR(36),
  user_type VARCHAR(36),
  active BOOLEAN,
  type VARCHAR(50),
  subject VARCHAR(36),
  language VARCHAR(50),
  selection_mode VARCHAR(20),
  skill VARCHAR(20)
);
