create table if not exists fact_pathway_learning_progress(
    dw_id                   bigint,
    _trace_id               varchar(36),
    event_type              varchar(100),
    created_time            timestamp,
    dw_created_time         timestamp,
    date_dw_id              bigint,
    experience_id           varchar(36),
    learning_session_id     varchar(36),
    content_id              varchar(36),
    learning_objective_id   bigint,
    student_dw_id           bigint,
    subject_dw_id           bigint,
    student_grade_dw_id     bigint,
    curriculum_subject_dw_id      bigint,
    curriculum_grade_dw_id  bigint,
    term_dw_id              bigint,
    tenant_dw_id            bigint,
    school_dw_id            bigint,
    student_section_dw_id   bigint,
    learning_path_dw_id     bigint,
    start_time              timestamp,
    end_time                timestamp,
    total_time              double precision encode bytedict,
    score                   integer,
    stars                   integer,
    lesson_type             varchar(50),
    retry                   boolean encode runlength,
    outside_of_school       boolean encode runlength,
    attempt                 integer,
    learning_experience_flag        boolean encode runlength,
    trimester_order         varchar(20),
    academic_year_dw_id     bigint,
    content_academic_year   varchar(20),
    time_spent              integer,
    instructional_plan_id   varchar(36),
    class_dw_id             bigint encode az64,
    lesson_category         varchar(40),
    level                   varchar(20),
    abbreviation            varchar(100),
    activity_template_id    varchar(100),
    activity_type           varchar(100),
    activity_component_type varchar(100),
    exit_ticket             boolean,
    main_component          boolean,
    completion_node         boolean,
    total_score             numeric(10, 4) encode az64,
    activity_completed      boolean,
    material_id             varchar(36),
    material_type           varchar(20),
    state                   smallint encode az64,
    total_stars             smallint encode az64,
    open_path_enabled       boolean     default false,
    source                  varchar(10),
    teaching_period_id      varchar(36),
    academic_year           varchar(10),
    assessment_id           varchar(36), --
    is_in_class_game_experience             boolean     default false,
    is_additional_resource  boolean     default false,
    bonus_stars             integer     default -1 encode az64,
    bonus_stars_scheme      varchar(40) default 'NA'::character varying
)
    sortkey (created_time, date_dw_id, school_dw_id, student_grade_dw_id, student_section_dw_id, student_dw_id, learning_session_id);
