package com.alefeducation.schema.activity


final case class ActivityMetadataEvent(lessonId: Long,
                                       activityUuid: String,
                                       activityTemplateUuid: String,
                                       code: String,
                                       description: String,
                                       title: String,
                                       activityType: String,
                                       boardId: Long,
                                       gradeId: Long,
                                       subjectId: Long,
                                       skillable: Boolean,
                                       thumbnailFileName: String,
                                       thumbnailContentType: String,
                                       thumbnailFileSize: Long,
                                       thumbnailLocation: String,
                                       thumbnailUpdatedAt: Long,
                                       userId: Long,
                                       academicYear: String,
                                       academicYearId: Long,
                                       maxStars: Int,
                                       lessonRoles: List[String],
                                       themeIds: List[Long],
                                       publisherId: Long,
                                       publishedDate: String,
                                       publishedBefore: Boolean,
                                       language: String,
                                       status: String,
                                       organisation: String,
                                       duration: Int,
                                       createdAt: Long,
                                       updatedAt: Long,
                                       occurredOn: Long,
                                       components: List[ActivityComponent])


final case class ActivityComponent(activityComponentType: String,
                                   activityTemplateComponentId: String,
                                   assignmentId: String,
                                   cclContentId: Long,
                                   description: String,
                                   location: String,
                                   mediaType: String,
                                   assessmentRules: List[ActivityAssessmentRule],
                                   stepUuid: String,
                                   title: String)

final case class ActivityAssessmentRule(difficultyLevel: String,
                                        id: String,
                                        poolId: String,
                                        poolName: String,
                                        questions: Int,
                                        resourceType: String)