package com.alefeducation.facts.learning_experience_v2.pathway

object LearningSessionTestUtils {

  val expLearningSessionCols = Set(
    "dw_id",
    "experience_id",
    "learning_session_id",
    "content_id",
    "instructional_plan_id",
    "learning_objective_id",
    "student_id",
    "date_dw_id",
    "subject_id",
    "student_grade_id",
    "tenant_id",
    "school_id",
    "class_id",
    "student_section",
    "curriculum_id",
    "curriculum_subject_id",
    "curriculum_grade_id",
    "learning_path_id",
    "academic_year_id",
    "event_type",
    "_trace_id",
    "trimester_order",
    "start_time",
    "end_time",
    "total_time",
    "score",
    "stars",
    "lesson_type",
    "retry",
    "outside_of_school",
    "attempt",
    "learning_experience_flag",
    "created_time",
    "dw_created_time",
    "content_academic_year",
    "time_spent",
    "lesson_category",
    "activity_template_id",
    "activity_type",
    "activity_component_type",
    "abbreviation",
    "exit_ticket",
    "main_component",
    "completion_node",
    "total_score",
    "total_stars",
    "activity_completed",
    "material_id",
    "material_type",
    "state",
    "activity_component_resources",
    "eventdate",
    "open_path_enabled",
    "source",
    "teaching_period_id",
    "academic_year",
    "bonus_stars_scheme",
    "bonus_stars"
  )

  val expExperienceCols: Set[String] = expLearningSessionCols + "level" + "score_breakdown" + "assessment_id"
}
