package com.alefeducation.schema.lps

sealed trait LearningProgressDomain {
  val occurredOn: String
  val attempt: Int
  val redo: Boolean
}

sealed trait LearningProgress extends LearningProgressDomain {
  val learningSessionId: String
  val schoolId: String
  val studentId: String
  val studentGrade: String
  val studentGradeId: String
  val studentSection: String
  val classId: String
  val subjectId: String
  val subjectCode: String
  val learningObjectiveId: String
  val lessonCategory: String
  val materialType: String
  val materialId: String
}

sealed trait LearningSession extends LearningProgress {
  val subjectName: String
  val learningObjectiveCode: String
  val learningObjectiveTitle: String
  val learningObjectiveType: String
  val trimesterId: String
  val trimesterOrder: Int
  val curriculumId: String
  val curriculumName: String
  val curriculumSubjectId: String
  val curriculumSubjectName: String
  val curriculumGradeId: String
  val learningPathId: String
  val instructionalPlanId: String
  val academicYearId: String
  val contentAcademicYear: String
  val teachingPeriodId: String
  val academicYear: String
}

sealed trait Experience extends LearningProgress {
  val experienceId: String
  val contentPackageId: String
  val contentId: String
  val contentTitle: String
  val lessonType: String
  val flag: String
  val contentPackageItem: ContentPackageItem
  val learningPathId: String
  val instructionalPlanId: String
  val academicYearId: String
  val contentAcademicYear: String
}

case class ActivityComponentResource(activityComponentType: String, exitTicket: Boolean)

case class LearningSessionStarted(occurredOn: String,
                                  attempt: Int,
                                  learningSessionId: String,
                                  studentId: String,
                                  studentGrade: String,
                                  studentGradeId: String,
                                  studentSection: String,
                                  classId: String,
                                  subjectId: String,
                                  subjectCode: String,
                                  subjectName: String,
                                  learningObjectiveId: String,
                                  learningObjectiveCode: String,
                                  learningObjectiveTitle: String,
                                  learningObjectiveType: String,
                                  schoolId: String,
                                  trimesterId: String,
                                  trimesterOrder: Int,
                                  curriculumId: String,
                                  curriculumName: String,
                                  curriculumSubjectId: String,
                                  curriculumSubjectName: String,
                                  curriculumGradeId: String,
                                  learningPathId: String,
                                  instructionalPlanId: String,
                                  redo: Boolean,
                                  academicYearId: String,
                                  contentAcademicYear: String,
                                  lessonCategory: String,
                                  activityTemplateId: String,
                                  activityType: String,
                                  activityComponentResources: List[ActivityComponentResource],
                                  materialType: String,
                                  materialId: String,
                                  openPathEnabled: Boolean,
                                  source: String,
                                  teachingPeriodId: String,
                                  academicYear: String,
                                  replayed: Boolean,
                                 )
    extends LearningSession

case class LearningSessionFinished(occurredOn: String,
                                   startTime: String,
                                   timeSpent: Int,
                                   attempt: Int,
                                   learningSessionId: String,
                                   studentId: String,
                                   studentGrade: String,
                                   studentGradeId: String,
                                   studentSection: String,
                                   classId: String,
                                   subjectId: String,
                                   subjectCode: String,
                                   subjectName: String,
                                   learningObjectiveId: String,
                                   learningObjectiveCode: String,
                                   learningObjectiveTitle: String,
                                   learningObjectiveType: String,
                                   schoolId: String,
                                   trimesterId: String,
                                   trimesterOrder: Int,
                                   curriculumId: String,
                                   curriculumName: String,
                                   curriculumSubjectId: String,
                                   curriculumSubjectName: String,
                                   curriculumGradeId: String,
                                   learningPathId: String,
                                   instructionalPlanId: String,
                                   redo: Boolean,
                                   score: Double,
                                   stars: Int,
                                   outsideOfSchool: Boolean,
                                   academicYearId: String,
                                   contentAcademicYear: String,
                                   lessonCategory: String,
                                   activityTemplateId: String,
                                   activityType: String,
                                   activityComponentResources: List[ActivityComponentResource],
                                   totalScore: Double,
                                   materialType: String,
                                   materialId: String,
                                   openPathEnabled: Boolean,
                                   source: String,
                                   teachingPeriodId: String,
                                   academicYear: String,
                                   replayed: Boolean,
                                   isAdditionalResource: Boolean,
                                   bonusStars: Int,
                                   bonusStarsScheme: String)
    extends LearningSession

case class ExperienceStarted(occurredOn: String,
                             attempt: Int,
                             schoolId: String,
                             experienceId: String,
                             learningSessionId: String,
                             studentId: String,
                             studentGrade: String,
                             studentGradeId: String,
                             studentSection: String,
                             classId: String,
                             subjectId: String,
                             subjectCode: String,
                             learningObjectiveId: String,
                             contentPackageId: String,
                             contentId: String,
                             contentTitle: String,
                             lessonType: String,
                             flag: String,
                             redo: Boolean,
                             retry: Boolean,
                             contentPackageItem: ContentPackageItem,
                             learningPathId: String,
                             instructionalPlanId: String,
                             academicYearId: String,
                             contentAcademicYear: String,
                             lessonCategory: String,
                             abbreviation: String,
                             activityType: String,
                             exitTicket: Boolean,
                             mainComponent: Boolean,
                             completionNode: Boolean,
                             activityComponentType: String,
                             materialType: String,
                             materialId: String,
                             openPathEnabled: Boolean,
                             source: String,
                             teachingPeriodId: String,
                             academicYear: String,
                             replayed: Boolean,
                             isInClassGameExperience: Boolean,
                             inClassGameOutcomeId: String)
    extends Experience

case class ExperienceFinished(occurredOn: String,
                              startTime: String,
                              timeSpent: Int,
                              attempt: Int,
                              schoolId: String,
                              experienceId: String,
                              learningSessionId: String,
                              studentId: String,
                              studentGrade: String,
                              studentGradeId: String,
                              studentSection: String,
                              classId: String,
                              subjectId: String,
                              subjectCode: String,
                              learningObjectiveId: String,
                              contentPackageId: String,
                              contentId: String,
                              contentTitle: String,
                              lessonType: String,
                              flag: String,
                              redo: Boolean,
                              contentPackageItem: ContentPackageItem,
                              learningPathId: String,
                              instructionalPlanId: String,
                              score: Double,
                              scoreBreakDown: List[ScoreBreakdownWithLessonIds],
                              scorePresent: Boolean,
                              outsideOfSchool: Boolean,
                              testId: String,
                              stars: Int,
                              suid: String,
                              trimesterOrder: Int,
                              curriculumId: String,
                              curriculumName: String,
                              curriculumSubjectId: String,
                              curriculumSubjectName: String,
                              curriculumGradeId: String,
                              academicYearId: String,
                              contentAcademicYear: String,
                              lessonCategory: String,
                              level: String,
                              abbreviation: String,
                              activityType: String,
                              exitTicket: Boolean,
                              mainComponent: Boolean,
                              completionNode: Boolean,
                              activityComponentType: String,
                              activityComponentResources: List[ActivityComponentResource],
                              totalScore: Double,
                              totalStars: Int,
                              activityCompleted: Boolean,
                              materialType: String,
                              materialId: String,
                              openPathEnabled: Boolean,
                              source: String,
                              teachingPeriodId: String,
                              academicYear: String,
                              replayed: Boolean,
                              isInClassGameExperience: Boolean,
                              inClassGameOutcomeId: String,
                              isAdditionalResource: Boolean,
                              bonusStars: Int,
                              bonusStarsScheme: String)
    extends Experience

case class ContentPackageItem(uuid: String,
                              contentUuid: String,
                              title: String,
                              lessonType: String,
                              contentType: String,
                              abbreviation: String)

// Few of the below fields in scoreBreakdown and attempts are optional.
// Using Double/Boolean data type, we are not able to query the parquet in S3 using spark.
// Using string for all fields works somehow.
case class ScoreBreakdown(id: String,
                          code: String,
                          timeSpent: String,
                          hintsUsed: String,
                          `type`: String,
                          version: String,
                          maxScore: String,
                          score: String,
                          isAttended: String,
                          attempts: List[Attempt])

case class ScoreBreakdownWithLessonIds(id: String,
                          code: String,
                          timeSpent: String,
                          hintsUsed: String,
                          `type`: String,
                          version: String,
                          maxScore: String,
                          score: String,
                          isAttended: String,
                          lessonIds: List[String],
                          learningOutcomes: List[LearningOutcome],
                          attempts: List[Attempt])

case class LearningOutcome(id: String, `type`: String)

case class Attempt(score: String, hintsUsed: String, isAttended: String, maxScore: String, suid: String, timestamp: String, timeSpent: String)

case class LessonFeedback(feedbackId: String,
                          schoolId: String,
                          academicYearId: String,
                          classId: String,
                          gradeId: String,
                          section: String,
                          subjectId: String,
                          trimesterId: String,
                          trimesterOrder: Int,
                          learnerId: String,
                          learningSessionId: String,
                          learningObjectiveId: String,
                          curriculumId: String,
                          curriculumGradeId: String,
                          curriculumSubjectId: String,
                          contentAcademicYear: String,
                          rating: Int,
                          ratingText: String,
                          comment: String,
                          instructionalPlanId: String,
                          learningPathId: String,
                          teachingPeriodId: String,
                          teachingPeriodTitle: String,
                          occurredOn: Long)

case class ExperienceSubmitted(uuid: String,
                               occurredOn: String,
                               attempt: Int,
                               experienceId: String,
                               learningSessionId: String,
                               learningObjectiveId: String,
                               studentId: String,
                               schoolId: String,
                               studentK12Grade: Int,
                               studentGradeId: String,
                               studentSection: String,
                               learningPathId: String,
                               instructionalPlanId: String,
                               subjectId: String,
                               subjectCode: String,
                               contentPackageId: String,
                               contentId: String,
                               contentTitle: String,
                               lessonType: String,
                               subjectName: String,
                               academicYearId: String,
                               contentAcademicYear: String,
                               classId: String,
                               outsideOfSchool: Boolean,
                               contentType: String,
                               lessonCategory: String,
                               startTime: String,
                               trimesterOrder: Int,
                               redo: Boolean,
                               suid: String,
                               abbreviation: String,
                               activityType: String,
                               exitTicket: Boolean,
                               mainComponent: Boolean,
                               completionNode: Boolean,
                               activityComponentType: String,
                               materialType: String,
                               materialId: String,
                               openPathEnabled: Boolean,
                               teachingPeriodId: String,
                               academicYear: String,
                               replayed: Boolean)

case class LearningContentStartSkipped(uuid: String,
                                       learningSessionId: String,
                                       learningObjectiveId: String,
                                       studentId: String,
                                       studentK12Grade: Int,
                                       studentGradeId: String,
                                       studentSection: String,
                                       learningPathId: String,
                                       instructionalPlanId: String,
                                       subjectCode: String,
                                       contentId: String,
                                       subjectName: String,
                                       schoolId: String,
                                       academicYearId: String,
                                       contentAcademicYear: String,
                                       classId: String,
                                       outsideOfSchool: Boolean,
                                       occurredOn: String)

case class LearningContentFinished(uuid: String,
                                   learningSessionId: String,
                                   learningObjectiveId: String,
                                   studentId: String,
                                   studentK12Grade: Int,
                                   studentGradeId: String,
                                   studentSection: String,
                                   learningPathId: String,
                                   instructionalPlanId: String,
                                   subjectCode: String,
                                   contentId: String,
                                   subjectName: String,
                                   schoolId: String,
                                   academicYearId: String,
                                   contentAcademicYear: String,
                                   classId: String,
                                   outsideOfSchool: Boolean,
                                   vendorData: VendorData,
                                   occurredOn: String)

case class VendorData(score: Double, timeSpent: Long)

final case class TotalScoreUpdatedEvent(uuid: String,
                                        occurredOn: String,
                                        attempt: Int,
                                        learningSessionId: String,
                                        learningObjectiveId: String,
                                        studentId: String,
                                        studentName: String,
                                        studentK12Grade: Int,
                                        studentGradeId: String,
                                        studentSection: String,
                                        learningPathId: String,
                                        instructionalPlanId: String,
                                        subjectId: String,
                                        subjectCode: String,
                                        subjectName: String,
                                        learningObjectiveCode: String,
                                        learningObjectiveTitle: String,
                                        learningObjectiveType: String,
                                        schoolId: String,
                                        trimesterId: String,
                                        trimesterOrder: Int,
                                        curriculumId: String,
                                        curriculumName: String,
                                        curriculumSubjectId: String,
                                        curriculumSubjectName: String,
                                        curriculumGradeId: String,
                                        academicYearId: String,
                                        contentAcademicYear: String,
                                        classId: String,
                                        startTime: String,
                                        outsideOfSchool: Boolean,
                                        practiceEnabled: Boolean,
                                        lessonCategory: String,
                                        activityTemplateId: String,
                                        activityType: String,
                                        stars: Int,
                                        score: Double,
                                        timeSpent: Int,
                                        totalScore: Double,
                                        activityCompleted: Boolean,
                                        eventRoute: String,
                                        eventSemanticId: String,
                                        studentGrade: String,
                                        redo: Boolean,
                                        activityComponents: List[ActivityComponent],
                                        materialType: String,
                                        materialId: String,
                                        openPathEnabled: Boolean,
                                        source: String,
                                        teachingPeriodId: String,
                                        academicYear: String,
                                        replayed: Boolean,
                                       )

final case class ActivityComponent(abbreviation: String,
                                   activityComponentId: String,
                                   activityComponentType: String,
                                   alwaysEnabled: Boolean,
                                   exitTicket: Boolean,
                                   mainComponent: Boolean)

case class ExperienceDiscarded(occurredOn: String,
                               startTime: String,
                               timeSpent: Int,
                               attempt: Int,
                               schoolId: String,
                               experienceId: String,
                               learningSessionId: String,
                               studentId: String,
                               studentGrade: String,
                               studentGradeId: String,
                               studentSection: String,
                               classId: String,
                               subjectId: String,
                               subjectCode: String,
                               learningObjectiveId: String,
                               contentPackageId: String,
                               contentId: String,
                               contentTitle: String,
                               lessonType: String,
                               flag: String,
                               redo: Boolean,
                               contentPackageItem: ContentPackageItem,
                               learningPathId: String,
                               instructionalPlanId: String,
                               score: Double,
                               scoreBreakDown: List[ScoreBreakdownWithLessonIds],
                               scorePresent: Boolean,
                               outsideOfSchool: Boolean,
                               testId: String,
                               stars: Int,
                               suid: String,
                               trimesterOrder: Int,
                               curriculumId: String,
                               curriculumName: String,
                               curriculumSubjectId: String,
                               curriculumSubjectName: String,
                               curriculumGradeId: String,
                               academicYearId: String,
                               contentAcademicYear: String,
                               lessonCategory: String,
                               level: String,
                               abbreviation: String,
                               activityType: String,
                               exitTicket: Boolean,
                               mainComponent: Boolean,
                               completionNode: Boolean,
                               activityComponentType: String,
                               activityComponentResources: List[ActivityComponentResource],
                               totalScore: Double,
                               activityCompleted: Boolean,
                               materialType: String,
                               materialId: String,
                               openPathEnabled: Boolean,
                               replayed: Boolean,
                               isInClassGameExperience: Boolean,
                               inClassGameOutcomeId: String)
  extends Experience


case class LearningSessionDeletedEvent (
  occurredOn: String,
  learningSessionId: String,
  learningObjectiveId: String,
  studentId: String,
  schoolId: String,
  studentGradeId: String,
  studentSection: String,
  learningPathId: String,
  instructionalPlanId: String,
  subjectId: String,
  subjectCode: String,
  subjectName: String,
  academicYearId: String,
  contentAcademicYear: String,
  classId: String,
  outsideOfSchool: Boolean,
  lessonCategory: String,
  activityType: String,
  materialType: String,
  materialId: String,
  attempt: Int,
  learningObjectiveCode: String,
  learningObjectiveTitle: String,
  learningObjectiveType: String,
  trimesterId: String,
  trimesterOrder: Int,
  curriculumId: String,
  curriculumName: String,
  curriculumSubjectId: String,
  curriculumSubjectName: String,
  curriculumGradeId: String,
  startTime: String,
  activityTemplateId: String,
  openPathEnabled: Boolean,
  studentGrade: String,
  teachingPeriodId: String,
  academicYear: String,
  replayed: Boolean,
 )
