package com.alefeducation.schema.practice

import com.alefeducation.schema.lps.ScoreBreakdown

case class Skill(uuid: String, code: String, name: String)

case class ItemContent(id: String, title: String, lessonType: String, location: String)

case class PracticeItem(learningObjectiveId: String,
                        learningObjectiveCode: String,
                        learningObjectiveTitle: String,
                        skills: List[Skill],
                        contents: List[ItemContent])

case class PracticeCreatedEvent(occurredOn: String,
                                created: String,
                                id: String,
                                learnerId: String,
                                subjectId: String,
                                subjectName: String,
                                schoolId: String,
                                gradeId: String,
                                grade: Int,
                                sectionId: String,
                                learningObjectiveId: String,
                                learningObjectiveCode: String,
                                learningObjectiveTitle: String,
                                skills: List[Skill],
                                saScore: Double,
                                items: List[PracticeItem],
                                academicYearId: String,
                                instructionalPlanId: String,
                                learningPathId: String,
                                classId: String,
                                materialId: String,
                                materialType: String)

case class PracticeSessionStarted(occurredOn: String,
                                  practiceId: String,
                                  learnerId: String,
                                  subjectId: String,
                                  subjectName: String,
                                  schoolId: String,
                                  gradeId: String,
                                  grade: Int,
                                  sectionId: String,
                                  learningObjectiveId: String,
                                  learningObjectiveCode: String,
                                  learningObjectiveTitle: String,
                                  skills: List[Skill],
                                  saScore: Double,
                                  created: String,
                                  updated: String,
                                  status: String,
                                  outsideOfSchool: Boolean,
                                  academicYearId: String,
                                  instructionalPlanId: String,
                                  learningPathId: String,
                                  classId: String,
                                  materialId: String,
                                  materialType: String)

case class PracticeSessionFinished(occurredOn: String,
                                   practiceId: String,
                                   learnerId: String,
                                   subjectId: String,
                                   subjectName: String,
                                   schoolId: String,
                                   gradeId: String,
                                   grade: Int,
                                   sectionId: String,
                                   learningObjectiveId: String,
                                   learningObjectiveCode: String,
                                   learningObjectiveTitle: String,
                                   skills: List[Skill],
                                   saScore: Double,
                                   created: String,
                                   updated: String,
                                   status: String,
                                   score: Double,
                                   outsideOfSchool: Boolean,
                                   stars: Int,
                                   academicYearId: String,
                                   instructionalPlanId: String,
                                   learningPathId: String,
                                   classId: String,
                                   materialId: String,
                                   materialType: String)

case class PracticeItemSessionStarted(occurredOn: String,
                                      practiceId: String,
                                      learningObjectiveId: String,
                                      learningObjectiveCode: String,
                                      learningObjectiveTitle: String,
                                      skills: List[Skill],
                                      status: String,
                                      practiceLearnerId: String,
                                      practiceSubjectId: String,
                                      practiceSubjectName: String,
                                      practiceSchoolId: String,
                                      practiceGradeId: String,
                                      practiceGrade: Int,
                                      practiceSectionId: String,
                                      practiceLearningObjectiveId: String,
                                      practiceLearningObjectiveCode: String,
                                      practiceLearningObjectiveTitle: String,
                                      practiceSkills: List[Skill],
                                      practiceSaScore: Double,
                                      outsideOfSchool: Boolean,
                                      practiceAcademicYearId: String,
                                      instructionalPlanId: String,
                                      learningPathId: String,
                                      practiceClassId: String,
                                      materialId: String,
                                      materialType: String)

case class PracticeItemSessionFinished(occurredOn: String,
                                       practiceId: String,
                                       learningObjectiveId: String,
                                       learningObjectiveCode: String,
                                       learningObjectiveTitle: String,
                                       skills: List[Skill],
                                       score: Double,
                                       practiceLearnerId: String,
                                       practiceSubjectId: String,
                                       practiceSubjectName: String,
                                       practiceSchoolId: String,
                                       practiceGradeId: String,
                                       practiceGrade: Int,
                                       practiceSectionId: String,
                                       practiceLearningObjectiveId: String,
                                       practiceLearningObjectiveCode: String,
                                       practiceLearningObjectiveTitle: String,
                                       practiceSkills: List[Skill],
                                       practiceSaScore: Double,
                                       outsideOfSchool: Boolean,
                                       practiceAcademicYearId: String,
                                       instructionalPlanId: String,
                                       learningPathId: String,
                                       practiceClassId: String,
                                       materialId: String,
                                       materialType: String
                                      )

case class PracticeItemContentSessionStarted(occurredOn: String,
                                             practiceId: String,
                                             id: String,
                                             title: String,
                                             lessonType: String,
                                             location: String,
                                             status: String,
                                             practiceLearnerId: String,
                                             practiceSubjectId: String,
                                             practiceSubjectName: String,
                                             practiceSchoolId: String,
                                             practiceGradeId: String,
                                             practiceGrade: Int,
                                             practiceSectionId: String,
                                             practiceLearningObjectiveId: String,
                                             practiceLearningObjectiveCode: String,
                                             practiceLearningObjectiveTitle: String,
                                             practiceSkills: List[Skill],
                                             practiceSaScore: Double,
                                             practiceItemLearningObjectiveId: String,
                                             practiceItemLearningObjectiveCode: String,
                                             practiceItemLearningObjectiveTitle: String,
                                             practiceItemSkills: List[Skill],
                                             outsideOfSchool: Boolean,
                                             practiceAcademicYearId: String,
                                             instructionalPlanId: String,
                                             learningPathId: String,
                                             practiceClassId: String,
                                             materialId: String,
                                             materialType: String)

case class PracticeItemContentSessionFinished(occurredOn: String,
                                              practiceId: String,
                                              id: String,
                                              title: String,
                                              lessonType: String,
                                              location: String,
                                              score: Double,
                                              scoreBreakdown: List[ScoreBreakdown],
                                              status: String,
                                              practiceLearnerId: String,
                                              practiceSubjectId: String,
                                              practiceSubjectName: String,
                                              practiceSchoolId: String,
                                              practiceGradeId: String,
                                              practiceGrade: Int,
                                              practiceSectionId: String,
                                              practiceLearningObjectiveId: String,
                                              practiceLearningObjectiveCode: String,
                                              practiceLearningObjectiveTitle: String,
                                              practiceSkills: List[Skill],
                                              practiceSaScore: Double,
                                              practiceItemLearningObjectiveId: String,
                                              practiceItemLearningObjectiveCode: String,
                                              practiceItemLearningObjectiveTitle: String,
                                              practiceItemSkills: List[Skill],
                                              outsideOfSchool: Boolean,
                                              practiceAcademicYearId: String,
                                              instructionalPlanId: String,
                                              learningPathId: String,
                                              practiceClassId: String,
                                              materialId: String,
                                              materialType: String)

case class NoMloForSkillsFound(occurredOn: Long,
                               learningObjectiveId: String,
                               learningObjectiveCode: String,
                               learningObjectiveTitle: String,
                               recommendedSkillsWithNoMlo: List[Skill]
                              )
