package com.alefeducation.schema.marketplace

case class ItemPurchasedEvent(purchaseId: String,
                              itemType: String,
                              itemId: String,
                              itemTitle: String,
                              itemDescription: String,
                              occurredOn: Long,
                              studentId: String,
                              redeemedStars: Int,
                              eventId: String,
                              gradeId: String,
                              sectionId: String,
                              schoolId: String,
                              academicYear: String,
                              transactionId: String,
                              academicYearId: String)


case class PurchaseTransactionEvent(studentId: String,
                                    availableStars: Int,
                                    itemCost: Int,
                                    starBalance: Int,
                                    itemId: String,
                                    itemType: String,
                                    gradeId: String,
                                    sectionId: String,
                                    schoolId: String,
                                    academicYear: String,
                                    transactionId: String,
                                    academicYearId: String,
                                    eventId: String,
                                    occurredOn: Long)

case class AvatarCreatedEvent(id: String,
                              `type`: String,
                              status: String,
                              name: String,
                              fileId: String,
                              description: String,
                              validFrom: String,
                              validTill: String,
                              organizations: List[String],
                              customization: List[String],
                              createdAt: String,
                              createdBy: String,
                              updatedAt: String,
                              updatedBy: String,
                              starCost: Int,
                              genders: List[String],
                              category: String,
                              tenants: List[String],
                              eventId: String,
                              occurredOn: Long,
                              isEnabledForAllOrgs: Boolean)

case class AvatarUpdatedEvent(id: String,
                              `type`: String,
                              status: String,
                              name: String,
                              fileId: String,
                              description: String,
                              validFrom: String,
                              validTill: String,
                              organizations: List[String],
                              customization: List[String],
                              createdAt: String,
                              createdBy: String,
                              updatedAt: String,
                              updatedBy: String,
                              starCost: Int,
                              genders: List[String],
                              category: String,
                              tenants: List[String],
                              eventId: String,
                              isEnabledForAllOrgs: Boolean,
                              occurredOn: Long)

case class AvatarDeletedEvent(id: String,
                              name: String,
                              fileId: String,
                              deletedBy: String,
                              deletedAt: String,
                              `type`: String,
                              category: String,
                              description: String,
                              validFrom: String,
                              validTill: String,
                              organizations: List[String],
                              customization: List[String],
                              starCost: Int,
                              genders: List[String],
                              tenants: List[String],
                              isEnabledForAllOrgs: Boolean,
                              eventId: String,
                              occurredOn: Long)

case class AvatarLayerCreatedEvent(id: String,
                                   configType: String,
                                   `type`: String,
                                   key: String,
                                   value: String,
                                   genders: List[String],
                                   cost: Int,
                                   tenants: List[String],
                                   tags: List[String],
                                   excludedOrganizations: List[String],
                                   isEnabled: Boolean,
                                   isDeleted: Boolean,
                                   validFrom: String,
                                   validTill: String,
                                   order: Int,
                                   eventId: String,
                                   occurredOn: Long)
