package com.alefeducation.facts.learning_experience

object LearningExperienceUtils {

  val expLearningSessionCols = Set(
    "fle_exp_id",
    "fle_ls_id",
    "fle_step_id",
    "fle_instructional_plan_id",
    "lo_uuid",
    "student_uuid",
    "fle_date_dw_id",
    "subject_uuid",
    "grade_uuid",
    "tenant_uuid",
    "school_uuid",
    "class_uuid",
    "section_uuid",
    "curr_uuid",
    "curr_subject_uuid",
    "curr_grade_uuid",
    "lp_uuid",
    "fle_academic_period_order",
    "fle_start_time",
    "fle_end_time",
    "fle_total_time",
    "fle_score",
    "fle_star_earned",
    "fle_lesson_type",
    "fle_is_retry",
    "fle_outside_of_school",
    "fle_attempt",
    "fle_exp_ls_flag",
    "fle_created_time",
    "fle_dw_created_time",
    "academic_year_uuid",
    "fle_content_academic_year",
    "fle_time_spent_app",
    "fle_lesson_category",
    "fle_activity_template_id",
    "fle_activity_type",
    "fle_activity_component_type",
    "fle_abbreviation",
    "fle_exit_ticket",
    "fle_main_component",
    "fle_completion_node",
    "fle_total_score",
    "fle_total_stars",
    "fle_is_activity_completed",
    "fle_material_id",
    "fle_material_type",
    "fle_state",
    "eventType",
    "fle_activity_component_resource",
    "eventdate",
    "fle_open_path_enabled",
    "fle_source",
    "fle_teaching_period_id",
    "fle_academic_year",
    "fle_is_additional_resource",
    "fle_bonus_stars_scheme",
    "fle_bonus_stars"
  )

  val expExperienceCols: Set[String] = expLearningSessionCols + "fle_adt_level" + "fle_score_breakdown" + "fle_assessment_id" + "fle_is_gamified"
}
