package com.alefeducation.schema.ktgame

case class ConsideredLO(id: String,
                        code: String,
                        title: String,
                        framework: String,
                        thumbnail: String,
                        ktCollectionId: String,
                        numberOfKeyTerms: String)

case class Question(`type`: String, time: String, min: String, max: String)

case class GameConfig(`type`: String, question: Question)

case class GameSessionCreatedEvent(occurredOn: String,
                                   created: String,
                                   gameSessionId: String,
                                   learnerId: String,
                                   subjectId: String,
                                   subjectName: String,
                                   subjectCode: String,
                                   consideredLos: List[ConsideredLO],
                                   gameConfig: GameConfig,
                                   trimesterId: String,
                                   trimesterOrder: Int,
                                   schoolId: String,
                                   gradeId: String,
                                   grade: Int,
                                   sectionId: String,
                                   gameType: String,
                                   academicYearId: String,
                                   instructionalPlanId: String,
                                   learningPathId: String,
                                   classId: String,
                                   materialId: String,
                                   materialType: String)

case class GameSessionStartedEvent(occurredOn: String,
                                   created: String,
                                   updated: String,
                                   gameSessionId: String,
                                   learnerId: String,
                                   subjectId: String,
                                   subjectName: String,
                                   subjectCode: String,
                                   trimesterId: String,
                                   trimesterOrder: Int,
                                   schoolId: String,
                                   gradeId: String,
                                   grade: Int,
                                   sectionId: String,
                                   status: String,
                                   gameType: String,
                                   outsideOfSchool: Boolean,
                                   academicYearId: String,
                                   instructionalPlanId: String,
                                   learningPathId: String,
                                   classId: String,
                                   materialId: String,
                                   materialType: String)

case class GameSessionFinishedEvent(occurredOn: String,
                                    created: String,
                                    updated: String,
                                    gameSessionId: String,
                                    learnerId: String,
                                    subjectId: String,
                                    subjectName: String,
                                    subjectCode: String,
                                    trimesterId: String,
                                    trimesterOrder: Int,
                                    schoolId: String,
                                    gradeId: String,
                                    grade: Int,
                                    sectionId: String,
                                    status: String,
                                    gameType: String,
                                    outsideOfSchool: Boolean,
                                    score: Double,
                                    stars: Int,
                                    academicYearId: String,
                                    instructionalPlanId: String,
                                    learningPathId: String,
                                    classId: String,
                                    materialId: String,
                                    materialType: String)

case class GameQuestionSessionStartedEvent(occurredOn: String,
                                           questionId: String,
                                           language: String,
                                           keyTermId: String,
                                           questionType: String,
                                           time: Double,
                                           learningObjectiveId: String,
                                           status: String,
                                           gameSessionId: String,
                                           learnerId: String,
                                           subjectId: String,
                                           subjectName: String,
                                           subjectCode: String,
                                           trimesterId: String,
                                           trimesterOrder: Int,
                                           schoolId: String,
                                           gradeId: String,
                                           grade: Int,
                                           sectionId: String,
                                           gameType: String,
                                           outsideOfSchool: Boolean,
                                           academicYearId: String,
                                           instructionalPlanId: String,
                                           learningPathId: String,
                                           classId: String,
                                           materialId: String,
                                           materialType: String)

case class GameQuestionSessionFinishedEvent(occurredOn: String,
                                            questionId: String,
                                            language: String,
                                            keyTermId: String,
                                            questionType: String,
                                            time: Double,
                                            learningObjectiveId: String,
                                            status: String,
                                            gameSessionId: String,
                                            learnerId: String,
                                            subjectId: String,
                                            subjectName: String,
                                            subjectCode: String,
                                            trimesterId: String,
                                            trimesterOrder: Int,
                                            schoolId: String,
                                            gradeId: String,
                                            grade: Int,
                                            sectionId: String,
                                            gameType: String,
                                            outsideOfSchool: Boolean,
                                            scoreBreakdown: ScoreBreakDown,
                                            academicYearId: String,
                                            instructionalPlanId: String,
                                            learningPathId: String,
                                            classId: String,
                                            materialId: String,
                                            materialType: String)

case class GameSessionCreationSkippedEvent(occurredOn: String,
                                           learnerId: String,
                                           subjectId: String,
                                           subjectName: String,
                                           subjectCode: String,
                                           consideredLos: List[ConsideredLO],
                                           trimesterId: String,
                                           trimesterOrder: Int,
                                           schoolId: String,
                                           gradeId: String,
                                           grade: Int,
                                           sectionId: String,
                                           gameConfig: GameConfig,
                                           academicYearId: String,
                                           instructionalPlanId: String,
                                           learningPathId: String,
                                           classId: String,
                                           materialId: String,
                                           materialType: String)

case class ScoreBreakDown(isAttended: Boolean, maxScore: String, score: Double, answer: String, answers: List[String], timeSpent: Double)
