name: Back Merge rc to develop
on:
  push:
    branches: [ rc ]
  workflow_call:
    secrets:
      ALEF_CI_DEVOPS_GITHUB_PAT:
        required: true

jobs:
  back-merge-rc-to-develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create PR to Back merge from rc to develop
        run: |
          git config --global user.email "alef-ci-devops@alefeducation.com"
          git config --global user.name "alef-ci-devops"
          git checkout develop
          git pull origin develop
          git checkout rc
          git checkout -b back_merge_${{ github.sha }}
          git merge develop --no-ff --commit --no-edit
          git push origin back_merge_${{ github.sha }}
          gh pr create --base develop --title "feat: [ALEF-0000] rc to develop" --body "" || echo "PR might be created already, trying to merge"
          echo "AUTO MERGE IS DISABLED AS THERE ARE MANDATORY CHECKS TO BE PASSED. MERGE THE GENERATED PR MANUALLY."
          gh pr merge --merge --auto
        env:
          GITHUB_TOKEN: ${{ secrets.ALEF_CI_DEVOPS_GITHUB_PAT }}
